version: "3"

services:
  focalboard:
    image: mattermost/focalboard
    container_name: focalboard
    depends_on:
      - focalboarddb
    env_file:
      - .env
    volumes:
      - ./config.json:/opt/focalboard/config.json
      - focalboard:/opt/focalboard/files
    restart: always
    networks:
      - internal
      - proxy

  focalboarddb:
    image: postgres:latest
    container_name: focalboarddb
    restart: always
    volumes:
      - focalboarddb:/var/lib/postgresql/data
    env_file:
      - .env
    networks:
      - internal

volumes:
  focalboard: {}
  focalboarddb: {}

networks:
  internal:
  proxy:
    external: true
